pipeline {
    agent any

    stages {
        stage('Running back-end unit tests') {
            steps {
               dir('bugtracker-backend'){
                sh'go test ./... -v'
               }
               
            }
        }
    }
}
