pipeline {
    agent any

    stages {
        //stage ('Running test in parrelel'){
           // parallel {
        //          stage('Running back-end unit tests') {
        //     agent {
        //         docker {
        //             image 'snakee/golang-junit:1.21'
        //             reuseNode true
        //         }
        //    }
        //     steps {
        //        dir('bugtracker-backend'){
        //         sh 'go test -v ./...'
        //        }
               
        //     }
        // }
        // stage('Running front-end unit tests') {
        //     agent {
        //         docker {
        //             image 'node:20-alpine'
        //             reuseNode true
        //         }
        //     }
        //     steps {
        //         dir('bugtracker-frontend'){
        //                 sh '''
        //             npm ci
        //             npm test
        //         '''
        //         }
            
        //        } 
        //      }
         
            //}
        //}
         stage("Launch Application"){
            agent{
                docker {
                    image'docker: 27.5.1'
                    reuseNode true
                    args '-v /var/run/docker.sock:/var/run/docker.sock -u 0'
                }
            }
            steps{
                sh 'docker compose up --build -d'
            }
         
         }
         stage('Run API test'){
            agent{
                docker{
                    image 'mcr.microsoft.com/playwright:v1.50.0-jammmy'
                    reuseNode true
                    args '-u 0 --network=host'
                }
            }
            steps {
                dir('tests-api'){
                    sh '''
                        npx wait-port http://localhost:8080/api/health -t 30000
                        npm ci
                        npx playwright test
                    '''
                }
            }
         }
            stage('E2E Tests'){
                agent {
                    docker {
                        image 'mcr.microsoft.com/playwright:v1.50.0-jammmy'
                        reuseNode true
                        args '-u 0 --network=host'
                    }
                }
                steps {
                    dir('tests-e2e'){
                    sh '''
                    npm ci
                    npx playwright test
                    '''
                    }
                    
                }
            }
            
            //This is to generate a report on jenkins, it is not complete 
            //It lacks an auto generated file from local tests run
            //post {
                //always {
                    //junit 'from parent to root FILE'
                    // publishHTML target: [
                    //     reportDir: ' from parent to root FOLDER'
                    //     reportFiles: 'file in the root folder'
                    //     reportName: 'name the test reports'
                    // ]
                //}
            //}
        }
    
    
    

    post {
        always{
            cleanWs()
        }
    }
}
